version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apiapp-app
    volumes:
      - ./src:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - laravel-network

  db:
    image: mysql:8.0
    container_name: apiapp-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      TZ: 'Asia/Tokyo'
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel-network
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: apiapp-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - laravel-network

volumes:
  db-data:

networks:
  laravel-network: