services:
  front:
    build: ./frontend
    volumes:
      - ./frontend:/workdir
    ports:
      - 3007:3000
  back:
    build: ./backend
    volumes:
      - ./backend:/workdir
    ports:
      - 8007:8000
  db:
    image: mysql:8.3
    volumes:
      - ./backend/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev
    ports:
      - 3307:3306 